### ISSUE TITLE
Potential dependency conflicts between c2c-template and pyyaml

### ISSUE THREAD

**Issue by NeolithEra** [camptocamp/c2c.template#65]
Hi, as shown in the following full dependency graph of  **_c2c-template_**, **_c2c-template_** requires _**pyyaml**_ (the latest version)， while the installed version of **_pyyaml-include _**(1.2) requires _**pyyaml>=3.12,<6.0**_.

According to Pip's “first found wins” installation strategy, _**pyyaml 5.3.1**_ is the actually installed version.  

Although the first found package version _**pyyaml 5.3.1**_ just satisfies the later dependency constraint （_**pyyaml>=3.12,<6.0**_), it will lead to a build failure once developers release a newer version of pyyaml.

### Dependency tree--------
```
c2c-template  - 2.2.1
| +- bottle(install version:0.12.18 version range:*)
| +- jinja2(install version:2.11.2 version range:*)
| | +- MarkupSafe(install version:2.0.0a1 version range:>=0.23)
| +- mako(install version:1.1.2 version range:*)
| | +- MarkupSafe(install version:2.0.0a1 version range:>=0.9.2)
| +- pyyaml(install version:5.3.1 version range:*)
| +- pyyaml-include(install version:1.2 version range:*)
| | +- PyYAML(install version:5.3.1 version range:>=3.12,<6.0)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_pyyaml_** to be **_<=5.3.1_**.
2.	Remove your direct dependency **_pyyaml_**, and use the **_pyyaml_** transitively introduced by **_pyyaml-include_**.
3.	Ask your direct dependency pyyaml-include to loosen the version range of **_pyyaml_** to be **_>=3.12_**.
@sbrunner  Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by sbrunner** [comment]
+1 for solution 2, thanks :-)
